# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'KMP Mobile Template' do
  	# Comment the next line if you don't want to use dynamic frameworks
  	use_frameworks!
  
  	pod 'common', :path => '../common'

  	pod 'PKHUD', '~> 5.0'
	pod 'Toast-Swift', '~> 5.0.1'

  	target 'KMP Mobile Template Tests' do
    	inherit! :search_paths
    		# Pods for testing
  	end

  	target 'KMP Mobile Template UITests' do
    		# Pods for testing
  	end
end
